# Welcome to Jekyll!

# Website settings
title: "Sandeep's Blog"
description: "Sandeep's blog,using Jekyll and github pages."
keywords: "sandeep,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://bsandyy.github.io"
url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  name: 'Sandeep'
  first_name: 'Sandeep'
  last_name: 'Bandi'
  email: 'bsandyy@gmail.com'
  facebook_username: 'bsandyy'
  github_username: 'bsandyy'
  head_img: 'static/img/landing/sand_c.png'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  blog: 'Blog'

# blog index
index:
  home: 'Home'
  python: 'Python'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'


# comment
disqus:
  name: bsandyy
  public_key: TD7uGS4tQxgsfv3jnSjXx4S5ZLdW7ORQTybs9TW0s0fyNDg4MCZNVazzUgj2jNps


# google analytics
ga:
  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
